---
galaxy_info:
  author: "gh_1mr"
  description: Install and configure fail2ban.
  min_ansible_version: "2.5"
  license: "MIT"
  platforms:
    - name: Debian
      versions:
        - stretch
        - buster
  galaxy_tags:
    - system
