---
galaxy_info:
  author: "gh_1mr"
  description: "vector.dev"
  min_ansible_version: "2.9"
  license: "MIT"
  platforms:
    - name: Debian
      versions:
        - stretch
        - buster
  galaxy_tags:
    - logs
