---
- name: Create directory
  ansible.builtin.file:
    path: /etc/update-motd.d
    state: directory

- name: Copy config files
  ansible.builtin.template:
    src: 00-header.j2
    dest: /etc/update-motd.d/00-header
    mode: '0755'
  notify: Update motd
