---
- name: Copy config file
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0755'

- name: Copy periodic config file
  ansible.builtin.copy:
    src: 02periodic
    dest: /etc/apt/apt.conf.d/02periodic
    owner: root
    group: root
    mode: '0755'
