---
- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - install_unattended
    - install

- name: Configure
  ansible.builtin.import_tasks: configure.yml
  tags:
    - configure_unattended
    - configure
