---
sql_exporter_version: '0.19.0'
sql_exporter_targz_url: 'https://github.com/burningalchemist/sql_exporter/releases/download/{{ sql_exporter_version }}/sql_exporter-{{ sql_exporter_version }}.linux-amd64.tar.gz'
sql_exporter_targz_sums: 'sha256:https://github.com/burningalchemist/sql_exporter/releases/download/{{ sql_exporter_version }}/sha256sums.txt'

sql_exporter_config_file: sql_exporter.yml
sql_exporter_user_name: sql_exporter
sql_exporter_service_name: sql_exporter
sql_exporter_systemd_unit: '/etc/systemd/system/{{ sql_exporter_service_name }}.service'

sql_exporter_dirs:
  binary_dir: /usr/local/bin
  config_dir: /etc/sql_exporter

sql_exporter_params:
  scrape_timeout: 15s
  scrape_timeout_offset: 500ms
  min_interval: 15s
  max_connections: 2
  max_idle_connections: 2
  max_connection_lifetime: 10m
