---
- name: Copy files to /etc/skel
  ansible.builtin.copy:
    src: etc/skel/{{ item }}
    dest: /etc/skel
  with_items:
    - .bashrc
    - .screenrc

- name: Copy scripts
  ansible.builtin.copy:
    src: usr/local/bin/{{ item }}
    dest: /usr/local/bin
    mode: '0755'
  with_items:
    - screen-mem-usage

- name: Copy bashrc to /root
  ansible.builtin.copy:
    src: root/.bashrc
    dest: /root/.bashrc

- name: Check existing users
  ansible.builtin.command: ls -1 /home
  register: users
  changed_when: false

- name: Copy files for existing users
  ansible.builtin.copy:
    src: etc/skel/{{ item.0 }}
    dest: /home/{{ item.1 }}
    owner: '{{ item.1 }}'
    group: '{{ item.1 }}'
  with_nested:
    - ['.bashrc', '.screenrc']
    - '{{ users.stdout_lines }}'
